Repository hanana1253/CrabBook, pull requests merged in 2021-11, with the labels that each got.

#5 Feature/kanban page
  .eslintrc.json
  package.json
  server.js
  src/html/kanban.html
  src/js/kanban.js
  src/js/kanban2.js
  src/scss/pages/_index.scss
  src/scss/pages/_kanban.scss
  src/scss/style.scss
  src/scss/utils/_mixin.scss
Labels: enhancement

#6 add: kanban2.js file
  src/js/kanban2.js
Labels: enhancement

#7 chore: update file constructure
  server.js
  src/html/linkCard.html
  src/html/statistics.html
  src/index.html
  src/js/components/kanban.js
  src/js/components/kanban2.js
  src/js/store/state.js
  src/js/utils/constants.js
  src/js/utils/helper.js
  src/scss/components/_index.scss
  src/scss/components/_linkCard.scss
  src/scss/components/_linkKanban.scss
  src/scss/components/_sidebar.scss
  src/scss/components/_statistics.scss
  src/scss/pages/_index.scss
  src/scss/utils/_color.scss
Labels: enhancement

#12 feat: merge kanban & sidebar
  .gitignore
  package-lock.json
  server.js
  src/html/kanban.html
  src/images/exit.png
  src/images/logo.png
  src/images/mypage.png
  src/js/components/kanban.js
  src/js/components/kanban2.js
  src/js/components/sidebar.js
  src/scss/components/_linkKanban.scss
  src/scss/components/_sidebar.scss
Labels: bug, enhancement

#16 feat: Add func to scrap open-graph
  server.js
  src/html/kanban.html
  src/js/components/Kanban.js
  src/js/components/kanban2.js
  src/js/components/main.js
  src/js/components/sidebar.js
  src/js/test.js
  src/js/view/render.js
  src/scss/components/_linkKanban.scss
  src/scss/components/_sidebar.scss
Labels: enhancement

#17 Implement LinkCard component
  src/html/linkCard.html
  src/js/components/LinkCard.js
  src/scss/components/_linkCard.scss
Labels: enhancement

#18 feat: Adapt LinkCard component
  src/js/components/Kanban.js
Labels: enhancement

#21 style: balance with layout propotion
  src/scss/components/_linkKanban.scss
  src/scss/components/_sidebar.scss
  src/scss/components/_statistics.scss
Labels: enhancement

#23 style: Update card width for fit on category column
  src/scss/components/_linkCard.scss
Labels: enhancement

#24 Update build option for using webpack
  .gitignore
  package-lock.json
  package.json
  src/index.html
  src/js/components/LinkCard.js
  src/js/components/main.js
  webpack.config.js
Labels: enhancement

#26 feat: Modularize files
  server.js
  src/html/kanban.html
  src/js/components/Kanban.js
  src/js/components/main.js
  src/js/store/state.js
  src/js/view/render.js
  src/scss/components/_linkCard.scss
  src/scss/components/_linkKanban.scss
  src/scss/components/_sidebar.scss
Labels: enhancement

#27 fix: Update proxy path
  webpack.config.js
Labels: enhancement

#31 Feature linkcard
  server.js
  src/images/thumbnail.png
  src/index.html
  src/js/components/Kanban.js
  src/js/components/LinkCard.js
  src/js/components/main.js
  src/js/view/render.js
  src/scss/components/_linkCard.scss
  webpack.config.js
Labels: enhancement

#32 Update UI for Kanban & mechanism for add category
  src/index.html
  src/js/components/main.js
  src/js/view/render.js
  src/scss/components/_linkCard.scss
  src/scss/components/_linkKanban.scss
  src/scss/components/_sidebar.scss
  src/scss/utils/_color.scss
Labels: enhancement

#35 feat: Add 3 Funcs
  package-lock.json
  package.json
  server.js
  src/html/kanban.html
  src/html/linkCard.html
  src/html/scraping.html
  src/html/sidebar.html
  src/html/statistics.html
  src/index.html
  src/js/components/Kanban.js
  src/js/components/main.js
  src/js/components/sidebar.js
  src/js/components/statistics.js
  src/js/store/mock.js
  src/js/store/state.js
  src/js/view/render.js
  src/scss/components/_linkKanban.scss
  src/scss/components/_sidebar.scss
Labels: bug, enhancement

#40 fix: minor bug
  server.js
  src/index.html
  src/js/components/main.js
  src/js/components/statistics.js
  src/js/view/render.js
  src/scss/components/_linkCard.scss
  src/scss/components/_linkKanban.scss
Labels: bug

#45 Update feature on linkcard
  server.js
  src/js/components/Kanban.js
  src/js/components/LinkCard.js
  src/js/components/main.js
  src/js/store/state.js
  src/scss/components/_linkCard.scss
Labels: enhancement

#46 refactor: page change function
  server.js
  src/index.html
  src/js/components/main.js
  src/scss/components/_recommend.scss
Labels: enhancement

#47 Align linkcard on different parent node, styling and structure
  src/js/view/render.js
  src/scss/components/_linkKanban.scss
  src/scss/components/_recommend.scss
Labels: bug, enhancement

#49 feat: add reset api delete link-card
  server.js
  src/js/components/LinkCard.js
  src/js/components/main.js
  src/js/components/recommend.js
  src/js/components/statistics.js
  src/js/store/state.js
Labels: enhancement

#50 style: update card's styling & add web font
  src/scss/components/_linkCard.scss
  src/scss/components/_linkKanban.scss
  src/scss/utils/_default.scss
Labels: enhancement

#54 feat: Width wheel scroll event
  .gitignore
  package-lock.json
  server.js
  src/js/components/main.js
  src/js/test.js
  src/js/utils/constants.js
  src/scss/components/_linkKanban.scss
  src/scss/components/_statistics.scss
Labels: bug, enhancement

#55 style: width profil chart
  src/scss/components/_statistics.scss
Labels: bug

#57 bug fix & update dummy datas
  server.js
  src/js/view/render.js
Labels: bug, enhancement
